### ISSUE TITLE
(backbone of damoyolo) image_size and input channel

### ISSUE THREAD

**Issue by ct-wei** [alibaba/lightweight-neural-architecture-search#13]
May I ask how to choose the image_size? Because the image_size seems to be different between https://github.com/tinyvision/DAMO-YOLO/blob/49dd0dbdcbf9ec67cb9c7b1ae2b571f71449b9db/configs/damoyolo_tinynasL20_T.py#L26 and 
https://github.com/alibaba/lightweight-neural-architecture-search/blob/6bf4d6949ed690b8ef59bcb843e2d36d03ebecd1/configs/damoyolo/damoyolo_k1kx_tiny.py#L9

Besides, I would like to ask why the input channel is 12 instead of 3 in https://github.com/alibaba/lightweight-neural-architecture-search/blob/6bf4d6949ed690b8ef59bcb843e2d36d03ebecd1/configs/damoyolo/damoyolo_k1kx_tiny.py#L15

**Comment by HYLcool** [comment]
Hi, @ct-wei 

Sorry for the misleading. We had a tutorial on NAS for DAMO-YOLO before, but it's removed after TinyNAS is updated to v2. This tutorial shows how we search backbones for DAMO-YOLO using TinyNAS v1 in detail.

In the item 2.i.a of [this section](https://github.com/alibaba/lightweight-neural-architecture-search/blob/c2eb1275f2e360edbb7b041000a40e45d7e65c02/scripts/damo-yolo/Tutorial_NAS_for_DAMO-YOLO_cn.md#%E6%B7%BB%E5%8A%A0%E8%BF%87%E7%A8%8B-1) from this tutorial, we explain that after searching we would replace the first Conv with a [Focus block](https://github.com/tinyvision/DAMO-YOLO/blob/49dd0dbdcbf9ec67cb9c7b1ae2b571f71449b9db/damo/base_models/core/ops.py#L152-L182), which can be simply regarded as a combination of pooling+Conv. During searching, we ignore the pooling operators in the Focus block and start the initial structure from the Conv in it. So the input size of the first Conv should be 320x320x12 instead of 640x640x3 when searching.

Of course, when we apply the searched structures in DAMO-YOLO, the actual input size of the whole backbone is still 640x640x3.
